DROP TABLE IF EXISTS films_users_likes CASCADE;
DROP TABLE IF EXISTS users_friend_list CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films_genres CASCADE;
DROP TABLE IF EXISTS films CASCADE;

CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR NOT NULL,
    description  VARCHAR(200),
    release_date DATE,
    duration     INTEGER CHECK (duration > 0),
    mpa_rating   VARCHAR
);


CREATE TABLE IF NOT EXISTS films_genres
(
    film_id INTEGER NOT NULL REFERENCES films (id),
    genre   VARCHAR NOT NULL UNIQUE,
    PRIMARY KEY (film_id, genre)
);

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(128) NOT NULL UNIQUE,
    login    VARCHAR(128) NOT NULL UNIQUE,
    name     VARCHAR      NOT NULL,
    birthday DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS users_friend_list
(
    from_user_id INTEGER NOT NULL REFERENCES users (id),
    to_user_id   INTEGER NOT NULL REFERENCES users (id),
    accepted     BOOLEAN NOT NULL,
    PRIMARY KEY (from_user_id, to_user_id)
);

CREATE TABLE IF NOT EXISTS films_users_likes
(
    film_id INTEGER NOT NULL REFERENCES films (id),
    user_id INTEGER NOT NULL REFERENCES users (id)
);